spring.application.name=HSF302_SE190588_RMS_PE
spring.config.import=optional:file:.env[.properties]

server.port=8080

spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=HSF302_2026_PE;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

payment.vnpay.enabled=${VNPAY_ENABLED:true}
payment.vnpay.return-url=${VNPAY_RETURN_URL:}
payment.vnpay.tmn-code=${VNPAY_TMN_CODE:}
payment.vnpay.hash-secret=${VNPAY_HASH_SECRET:}
